pipeline {
  agent any
  dir("my-app"){
    stages { 
     stage ('Clean') {
       steps {
        
         sh 'mvn clean' 
       } 
     } 
     stage ('Test') { 
       steps {
         sh 'mvn test' 
       } 
    
     } 
     stage('Package') { 
       steps {
         sh 'mvn package' 
        }
     }
     }
   }
 }
