pipeline {
  agent any
  stages { 
    stage ('Clean') {
      steps {
        sh 'mvn clean --file pom.xml' 
      } 
    } 
    stage ('Test') { 
      steps {
        sh 'mvn test' 
      } 
    
    } 
    stage('Package') { 
      steps {
        sh 'mvn package' 
       }
    }
  }
}
